FROM jboss/keycloak@sha256:abdb1aea6c671f61a594af599f63fbe78c9631767886d9030bc774d908422d0a

USER root
RUN rm -f /etc/os-release /usr/lib/os-release /etc/system-release-cpe /etc/redhat-release
USER 1000
