FROM ubuntu:24.04@sha256:c279a739b31ead4ebc3e9ce04937eb8b612799b52c26133eb3b4a056d08c31a6

# this will associate the image with the test-images repository in ghcr.io
LABEL org.opencontainers.image.source=https://github.com/anchore/test-images
