FROM alpine:3.12
WORKDIR /home
COPY ./test_aws_secret_key test_aws_secret_key
COPY ./test_aws_access_key test_aws_access_key
COPY ./test_api_key test_api_key
COPY ./test_docker_config.json test_docker_config
COPY ./test_rsa_key test_rsa_key
