# Photon OS 4.0 test image with known vulnerable packages
# Pin base image by digest (4.0-20240728) to lock package versions
FROM photon:4.0@sha256:88fccf9e63c2996b8d58ee506e0634def6aa20221ba367e2f63f3a39858de60e
LABEL maintainer="Anchore Test"
